//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webintern.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNSEntities1 : DbContext
    {
        public QLNSEntities1()
            : base("name=QLNSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bangluong> bangluongs { get; set; }
        public virtual DbSet<leave_requests> leave_requests { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<phongban> phongbans { get; set; }
        public virtual DbSet<user_accounts> user_accounts { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
    }
}
